#===================================================================
# Spring Boot application configuration for development environment
#===================================================================

server:
  port: 9090

spring:
  application:
    name: to-do list API

  profiles:
    active: qa

  # Database configuration
  datasource:
    url: jdbc:postgresql://${MyServer.Database.HOST}/${MyServer.Database.DBNAME}
    username: ${MyServer.Database.USER}
    password: "${MyServer.Database.PASS}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  # Keycloak configuration
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${MyConfig.Keycloak.CLIENTID}
            client-secret: ${MyConfig.Keycloak.CLIENTSECRET}
            provider: keycloak
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: ${MyConfig.Keycloak.ISSUERURI}
      resourceserver:
        jwt:
          issuer-uri: ${MyConfig.Keycloak.ISSUERURI}

  jwt:
    auth:
      converter:
        resource-id: ${MyConfig.Keycloak.CLIENTID}
        principle-attribute: preferred_username